I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 168, in script
    with di
  File "game/script.rpy", line 168, in <module>
    with di
NameError: name 'di' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 168, in script
    with di
  File "/Applications/renpy-8.2.1-sdk/renpy/ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Applications/renpy-8.2.1-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-8.2.1-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 168, in <module>
    with di
NameError: name 'di' is not defined

macOS-14.3.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
Beyond Stars HD 1.0
Tue Apr 16 04:01:47 2024
